// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MFD_Thingy.DB.Context
{
    public partial class Action
    {
        public Action()
        {
            Control_Actions = new HashSet<Control_Action>();
        }

        public string Name { get; set; }
        public string Interaction { get; set; }
        public string Modifier { get; set; }

        public int Id { get; set; }
        public int? AppId { get; set; }
        public int? HoldTime { get; set; }
        public int? Type { get; set; }
        public int? ScreenId { get; set; }

        public virtual Application App { get; set; }
        public virtual ICollection<Control_Action> Control_Actions { get; set; }
    }
}