// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MFD_Thingy.DB.Context
{
    public partial class Screen_Control
    {
        public Screen_Control()
        {
            Control_Actions = new HashSet<Control_Action>();
        }

        public int? Position { get; set; }
        public string Name { get; set; }
        public int Id { get; set; }
        public int? ScreenId { get; set; }
        public int? ThemeId { get; set; }
        
        

        public virtual Screen Screen { get; set; }
        public virtual ICollection<Control_Action> Control_Actions { get; set; }
    }
}