// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MFD_Thingy.DB.Context
{
    public partial class Screen
    {
        public Screen()
        {
            Screen_Items = new HashSet<Screen_Control>();
        }

        public int Id { get; set; }
        public int? AppId { get; set; }
        public int? ThemeId { get; set; }
        public string Name { get; set; }
        //public bool Ovrd_Item_MinWidth { get; set; }
        //public int? Ovrd_Item_MinWidth_Val { get; set; }
        //public bool Ovrd_Item_Spacing { get; set; }
        //public int? Ovrd_Item_Spacing_Val { get; set; }
        //public bool Ovrd_Color_Background { get; set; }
        //public string Ovrd_Color_Background_Val { get; set; }
        //public bool Ovrd_Color_Forground { get; set; }
        //public string Ovrd_Color_Forground_Val { get; set; }
        //public bool Ovrd_Color_ScreenBackground { get; set; }
        //public string Ovrd_Color_ScreenBackground_Val { get; set; }

        public virtual Application App { get; set; }
        public virtual ICollection<Screen_Control> Screen_Items { get; set; }
    }
}