// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MFD_Thingy.DB.Context
{
    public partial class Theme
    {
        public int Id { get; set; }
        public int? AppId { get; set; }
        public string Name { get; set; }
        public string Color_ScreenBackground { get; set; }
        public string Color_Background { get; set; }
        public string Color_Forground { get; set; }
        public int? Item_MinWidth { get; set; }
        public int? Item_Spacing { get; set; }

        public virtual Application App { get; set; }
    }
}